version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: test-redis
    restart: always
    ports:
      - "6222:6379"
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
