spring:
  datasource:
    url: jdbc:h2:mem:teamfresh
    driver-class-name: org.h2.Driver
    username: teamfresh
    password: teamfresh
  h2:
    console:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  docker:
    compose:
      enabled: true
      start:
        command: up
      stop:
        command: down
      lifecycle-management: start_and_stop
  jpa:
    defer-datasource-initialization: true
