INSERT INTO product (name, stock, created_at, modified_at)
VALUES
    ('사과', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('바나나', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('파인애플', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('키위', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('딸기', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('수박', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('멜론', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('포도', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('복숭아', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('체리', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
